### ISSUE TITLE
Use threading around DataManager

### ISSUE THREAD

**Issue by stephenjust** [CMPUT301F14T14/android-question-answer-app#115]
Once the RemoteDataStore works, there will be noticeable delay on the UI thread until we encapsulate all calls to DataManager inside threads.

The team who takes on this task must use either Runnables, AsyncTasks, or RxJava's threading to run all DataManager calls on a separate thread.

**Comment by RyanKusters** [comment]
both of you!

**Comment by stephenjust** [comment]
Pretty sure this is done.
