### ISSUE TITLE
DataManager object consistency

### ISSUE THREAD

**Issue by stephenjust** [CMPUT301F14T14/android-question-answer-app#116]
Because MVC expects existing model objects to be updated with new data, rather than creating new objects to replace old ones, we need to be able to pass existing objects into GSON so that new data may be deserialized into the existing objects. This will require some changes to DataManager and LocalDataStore.

**Comment by RyanKusters** [comment]
How are we implementing the update when connection restablished? is there a list of things to upload?

**Comment by stephenjust** [comment]
I am under the impression that most of the actions will need to be
rewritten in command pattern so that transactions can be recorded. Unless
someone has a better idea.

**Comment by RyanKusters** [comment]
Could it be sufficient to have a list of UUID for everything added during offline activity. Then when the online connection is established the remote data manager can traverse the list of UUID pushing each corresponding object to elastisearch and "on success" remove that UUID from the list. This of course means the local data store will hold the object until then. But after the upload, the local data manager could traverse the lists of necessary data and then remove what is no longer needed locally.

**Comment by stephenjust** [comment]
That works for additions, but will probably break for up votes. But that
could be solved with an offline up vote list.

**Comment by RyanKusters** [comment]
This has been done and re done with further developments.
