### ISSUE TITLE
Store image data on ES

### ISSUE THREAD

**Issue by stephenjust** [CMPUT301F14T14/android-question-answer-app#117]
We need to store image data somehow on elasticsearch.

ES does not support raw binary data, so it needs to be encoded.
My recommendation is a new document type, which will store the image in base64 encoded text.

**Comment by Cotto4** [comment]
I'm hoping that somebody can verify that this is actually working as intended. My emulator doesn't do it so nicely, maybe somebody with a phone?

**Comment by stephenjust** [comment]
I can verify that it is NOT working as intended. I see no image data at all
on ES.

## 

Stephen Just

**Comment by Cotto4** [comment]
Can you check the serialization hookup Stephen and see if I made a mistake somewhere?

**Comment by stephenjust** [comment]
Already working on it.

(Struggling to select an image at all right now...)

## 

Stephen Just
