### ISSUE TITLE
Implement Geolocation followthrough in local data store

### ISSUE THREAD

**Issue by RyanKusters** [CMPUT301F14T14/android-question-answer-app#139]

**Comment by stephenjust** [comment]
There is nothing to do here.

**Comment by RyanKusters** [comment]
Then how does the app capture and retain the Geo-location data for the posts?

**Comment by linster** [comment]
Isn't it just a property in each type of model object?

**Comment by RyanKusters** [comment]
Oh I see. It would be captured just like the body text.
