### ISSUE TITLE
Implement search by geolocation (near Me)

### ISSUE THREAD

**Issue by RyanKusters** [CMPUT301F14T14/android-question-answer-app#141]

**Comment by linster** [comment]
@sdwowk  and @linster will be working with this. 

http://www.elasticsearch.org/blog/geo-location-and-search/

(near Me) will arbitrarily be defined to 30km distance from a pin. If we had more time, we could have dialog with a slider, yadda yadda. Time constraints.

**Comment by linster** [comment]
@stephenjust HALP!!!!?! You are the ES GOD!

Can you do an ES query that does this?

{
    "filtered" : {  ///I DUNNO WHAT FILTERED DOES??? 
        "query" : {
            "field" : { "text" : "restaurant" }
        },
        "filter" : {
            "geo_distance" : {
                "distance" : "30km",
                "pin.location" : {
                    "lat" : VALUEFROMLOCATIONLAT,
                    "lon" : VALUEFROMLOCATIONLON
                }
            }
        }
    }
}

**Comment by stephenjust** [comment]
Do you have a shared branch that I can write to?

## 

Stephen Just

**Comment by linster** [comment]
Scott is about to pull request the latest code.

**Comment by stephenjust** [comment]
The query is written.

Can't test it yet because I'm missing some files in your branch.

**Comment by linster** [comment]
OMG YAY!!!!! We are very close. Now reading out locations correctly. Some testing!!!!!! Seems to be working!?!?!?!?!!!!!!

**Comment by stephenjust** [comment]
Can someone with location set up test this?

**Comment by sdwowk** [comment]
Works!
