### ISSUE TITLE
Create Answer Fragment

### ISSUE THREAD

**Issue by lamorie** [CMPUT301F14T14/android-question-answer-app#15]

**Comment by Cotto4** [comment]
Hey guys, with regards to this, how are we implementing with the list adapter? I may be misunderstanding fragments, but to my knowledge the item in the answer list should be a fragment itself. Right now it is implemented as just the answer fields, should we re-implement that to be a fragment?

**Comment by stephenjust** [comment]
The item in the answer list is a small view but technically not a fragment.
Clicking on it would open a dialog fragment or an activity, and I think
that this is what the issue refers to.
