### ISSUE TITLE
search does nothing, all searches return empty

### ISSUE THREAD

**Issue by RyanKusters** [CMPUT301F14T14/android-question-answer-app#166]

**Comment by stephenjust** [comment]
Does this work now? It should be fine...

**Comment by lamorie** [comment]
it returns something now, but doesn't really work... it changes the question title to whatever you searched and you can't view the question

**Comment by stephenjust** [comment]
I think this is @sdwowk 's issue as it is part of search activity.

**Comment by sdwowk** [comment]
Any ideas on why the onClickListener is not working?
