### ISSUE TITLE
Favorite a question that has already been favorited crashes the app

### ISSUE THREAD

**Issue by Cotto4** [CMPUT301F14T14/android-question-answer-app#184]
Unless I'm high

**Comment by sdwowk** [comment]
Odd but the question is a null pointer exception

**Comment by stephenjust** [comment]
There's some desync between ES and your device. Obviously our app doesn't
handle me clearing the ES database very well.

## 

Stephen Just

**Comment by Cotto4** [comment]
So is this not an actual issue then? Just me?

**Comment by stephenjust** [comment]
Maybe. Everyone has to have all of their phones cleared at the same time as
I clear ES, AND be on the latest version of the app.

## 

Stephen Just

**Comment by stephenjust** [comment]
Cannot reproduce on my own question.

**Comment by sdwowk** [comment]
Ok, so we pass the question Id through the intent to question activity. and we use question.getID() to favourite the questions, if we are having latency issues why don't we use questionID that was passed through the intent instead of question.getId()??

**Comment by sdwowk** [comment]
Are any of you at school right now?

**Comment by stephenjust** [comment]
Stefan, ryan and I are in CompE club.

## 

Stephen Just

**Comment by stephenjust** [comment]
Closed norep
