### ISSUE TITLE
Updating UML?

### ISSUE THREAD

**Issue by Cotto4** [CMPUT301F14T14/android-question-answer-app#211]
Is this a thing that we should be doing? Maybe just autogenerate it?

**Comment by RyanKusters** [comment]
The requirements say yes.

**Comment by sdwowk** [comment]
Why is this assigned to me? I do not know how to auto generate the UML!!!!!

**Comment by Cotto4** [comment]
Anybody have a chance to get to the lab machines quick? I won't be able to make it quite in time.

**Comment by sdwowk** [comment]
If someone can just make the UML and push it to the wiki I can organize it

**Comment by RyanKusters** [comment]
@linster and I have done this with eUML2.

**Comment by sdwowk** [comment]
looks beautiful
