### ISSUE TITLE
Display search results

### ISSUE THREAD

**Issue by stephenjust** [CMPUT301F14T14/android-question-answer-app#32]

**Comment by sdwowk** [comment]
I think stephens latest pull request incorporated this....

**Comment by stephenjust** [comment]
No.

**Comment by stephenjust** [comment]
@sdwowk Can you connect your search interface to the search class I wrote?

**Comment by sdwowk** [comment]
Yes, I shall work on this tonight

**Comment by sdwowk** [comment]
done! just merge
