### ISSUE TITLE
Send search query to server and read results

### ISSUE THREAD

**Issue by stephenjust** [CMPUT301F14T14/android-question-answer-app#34]
This search task is limited to server communication

**Comment by linster** [comment]
@stephenjust , does #159 cover this issue?

**Comment by stephenjust** [comment]
No it does not cover this issue.

**Comment by stephenjust** [comment]
Mostly covered by #161 - The approach I took will need a little more effort in the views, but it should be easier than having to have a list adapter with mixed types in it.

**Comment by sdwowk** [comment]
I think this is done, There are other issues that cover fixing the bugs...
